cities = read.csv('C:/Users/daria/Desktop/Projekt/dane0.csv', sep=";", header=TRUE)
cities.use = cities[,-c(1)]
medians = apply(cities.use,2,median)
mads = apply(cities.use,2,mad)
cities.scaled = scale(cities.use,center=medians,scale=mads) 
cities.scaled.dist = dist(cities.scaled,method="manhattan")
cities.scaled.hclust = hclust(cities.scaled.dist, method="ward.D")
plot(cities.scaled.hclust, hang = -1, cex = 0.6)
rect.hclust(cities.scaled.hclust, k=10) 
categories = data.frame(cities$nazwa, cutree(cities.scaled.hclust,10))
write.csv2(categories, file = "C:/Users/daria/Desktop/Projekt/categories.csv")
bmp("C:/Users/daria/Desktop/Projekt/dane0-plot.bmp", width = 15000, height = 3000)
plot(cities.scaled.hclust, labels=cities$nazwa, hang = -1, cex = 0.6)
rect.hclust(cities.scaled.hclust, k=10)
dev.off()